version: '3.8'

services:
  flake8:
    build:
      context: ../../
      dockerfile: contrib/docker/flake8/Dockerfile

  image_tool:
    build:
      context: ../../
      dockerfile: contrib/docker/image_tool/Dockerfile
    command: python src/main.py
    environment:
      - "DOCKER_ENV=true"
      - DISPLAY=${DISPLAY}
    volumes:
      - ../../:/app/TestTask
      - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  elk:
    driver: bridge
